version: '3.8'

services:

  
    
  searchrepository.api:
    image: ${DOCKER_REGISTRY-}searchrepositoryapi
    build:
      context: .
      dockerfile: SearchRepository.API/Dockerfile
    ports:
      - '5080:5080'

  react:
    build: 
        context: ./searchrepository.react
        dockerfile: Dockerfile
    ports:
        - '3000:3000'
    stdin_open: true
    tty: true
