﻿networks:
  network:


services:
  
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    networks:
      - network
    volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
      - react
  
  react:
    build: 
      context: ./searchrepository.react
    container_name: react
    ports:
      - '3000:3000'
    stdin_open: true
    networks:
      - network
    tty: true
  
  api:
    container_name: SearchRepositoryAPI
    image: searchrepository.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: SearchRepository.API/Dockerfile
    ports:
      - "5080:5080"
    networks:
      - network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
        
    