version: '3.8'

networks:
  network:

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    networks:
      - network
    depends_on:
      - searchrepository.api
    
  searchrepository.api:
    image: ${DOCKER_REGISTRY-}searchrepositoryapi
    build:
      context: .
      dockerfile: SearchRepository.API/Dockerfile
    ports:
      - '5080:5080'
    networks:
      - network

  react:
    build: 
        context: ./searchrepository.react
        dockerfile: Dockerfile
    ports:
        - '3000:3000'
    stdin_open: true
    tty: true
    networks:
      - network
  db:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
